<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_back to simulator</name>
   <tag></tag>
   <elementGuidId>c6bc9d50-b9e7-424d-91d6-98935741078e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Back to Simulator']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.btn.btn-primary.col-4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4df77430-e13d-486e-b176-e63860fae788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>doSubmit();</value>
      <webElementGuid>a395a1ae-222f-4360-8446-5355bcb72cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Back to Simulator</value>
      <webElementGuid>71d86117-9c87-4d3d-a888-99ad307365de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary col-4</value>
      <webElementGuid>c7f96a3a-a308-433c-9a2f-0bff6f094914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>5de9ee07-921d-4b74-8676-8ab206c8094e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainForm&quot;)/div[@class=&quot;col-12 p-2 mt-3 align-items-center&quot;]/center[1]/div[@class=&quot;col-11 shadow p-3 mb-5 bg-white rounded border border-warning&quot;]/div[@class=&quot;d-flex justify-content-center form-row col-12&quot;]/div[@class=&quot;d-flex justify-content-center form-group col-10&quot;]/input[@class=&quot;btn btn-primary col-4&quot;]</value>
      <webElementGuid>786b6f55-cc0b-41f6-ade4-5edceba30e1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Back to Simulator']</value>
      <webElementGuid>b4f5001e-2b36-4eaa-b979-3593887c9367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MainForm']/div[2]/center/div/div/div[5]/input</value>
      <webElementGuid>29d38982-1e20-44a4-b4ce-789ad80a598e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>a0e801c8-be59-409f-ba5a-eb480dd39bca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit']</value>
      <webElementGuid>e24501f6-061e-4d51-ae77-d0167d812858</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
