<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>vaadin-text-field_1</name>
   <tag></tag>
   <elementGuidId>c2a6bf35-06ca-4dc4-bb0d-d07f6f92395e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//vaadin-text-field[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>vaadin-text-field</value>
      <webElementGuid>570f2d60-6c44-44ca-a81d-29f968de2adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>24096584-c475-4f6e-8842-9d308619b70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main-layout&quot;]/vaadin-vertical-layout[1]/vaadin-vertical-layout[1]/vaadin-vertical-layout[1]/vaadin-horizontal-layout[1]/vaadin-text-field[2]</value>
      <webElementGuid>a69d5c4d-f652-4dfc-9102-a2f63052d604</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//vaadin-text-field[2]</value>
      <webElementGuid>c87d994a-9105-4391-9568-75c3bf3b117e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
