<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Transaction Report</name>
   <tag></tag>
   <elementGuidId>47d300a6-14db-4399-a0ae-2fd6c58beb97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='menu-4001']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#menu-4001 > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b9493e4d-0615-4a73-9f22-f2f2a0cfe29e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/merchant-ss-app/en/transactionlist</value>
      <webElementGuid>ce8d420f-3905-4bfe-aed5-b71001545616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Transaction Report</value>
      <webElementGuid>93e78816-29d3-41bf-9930-4945da02922e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menu-4001&quot;)/a[1]</value>
      <webElementGuid>982ca26c-2f1f-4661-8d07-ddccb295a16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cek Transaksi/menu_transaction report</value>
      <webElementGuid>1f3dbed3-4c09-47e0-8a61-11e2ace0db9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='menu-4001']/a</value>
      <webElementGuid>4ed42113-b86c-492e-95d5-bbbfa7a7ae3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Transaction Report')]</value>
      <webElementGuid>3bcb998a-6ed9-4274-b2e5-556157667048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Report'])[1]/following::a[1]</value>
      <webElementGuid>a252f0f7-70bd-4897-9336-9b070b3af545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administration'])[1]/preceding::a[1]</value>
      <webElementGuid>c2c23175-521e-4154-ae2c-db374268363c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/merchant-ss-app/en/transactionlist')]</value>
      <webElementGuid>27249107-1298-4821-bfba-7431a0a783a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li/a</value>
      <webElementGuid>7644bca6-a79b-4c5a-ab6b-926464091f5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/merchant-ss-app/en/transactionlist' and (text() = ' Transaction Report' or . = ' Transaction Report')]</value>
      <webElementGuid>994e42b2-e0af-4757-804b-1030019a94f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
