<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SUCCESS</name>
   <tag></tag>
   <elementGuidId>ace9cd7f-02a0-4ea5-ab29-edf11024f31f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/div[2]/table/tbody/tr/td[14]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.label-active</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4d920d29-9317-4658-9743-020ff3746859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-active</value>
      <webElementGuid>9f09b927-e480-4c36-8a78-5819b894887c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SUCCESS</value>
      <webElementGuid>09f75366-51ed-4333-bb77-eec353766b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;isi&quot;]/div[@class=&quot;my-card&quot;]/table[@class=&quot;table table-hover table-responsive mt-3&quot;]/tbody[1]/tr[1]/td[14]/div[@class=&quot;label-active&quot;]</value>
      <webElementGuid>fc98911c-6d03-4941-9488-37b0877bcb44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cek Transaksi/status_sukses</value>
      <webElementGuid>8178c4b1-feb9-4f56-8ee2-d1aba8589a60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/table/tbody/tr/td[14]/div</value>
      <webElementGuid>c63695db-5455-4cc6-a30d-1a7c815a5c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIRTUAL ACCOUNT'])[1]/following::div[1]</value>
      <webElementGuid>09375e76-c643-49cb-802b-b0f70f736334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BCA Virtual Account'])[2]/following::div[2]</value>
      <webElementGuid>a46638c2-cc1c-4ed1-8069-061ff39ff04e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backend Notification'])[1]/preceding::div[1]</value>
      <webElementGuid>93a89586-f8a7-47bc-937d-e2e1a318c92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SUCCESS']/parent::*</value>
      <webElementGuid>ba0112ae-4d41-4974-9f35-470dd8f68696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[14]/div</value>
      <webElementGuid>0906f420-0c9a-40f9-b219-ceb24f04b364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'SUCCESS' or . = 'SUCCESS')]</value>
      <webElementGuid>c2865056-0049-4af9-bd7c-032a43685129</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
