<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_PENDING</name>
   <tag></tag>
   <elementGuidId>f8fe989b-ff45-4df9-9685-a33b326e7e4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/div[2]/table/tbody/tr[3]/td[14]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.label-pending</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2ad7e647-e130-403c-85f6-7f407c5eedd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>label-pending</value>
      <webElementGuid>07c25530-6824-496a-9aef-516154196615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PENDING</value>
      <webElementGuid>273f0f2a-7409-402a-871d-34a01b505800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;isi&quot;]/div[@class=&quot;my-card&quot;]/table[@class=&quot;table table-hover table-responsive mt-3&quot;]/tbody[1]/tr[3]/td[14]/div[@class=&quot;label-pending&quot;]</value>
      <webElementGuid>92a0bf2f-1209-451c-ae3b-e3368f9a5c1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Cek Transaksi/status_pending</value>
      <webElementGuid>5dbc3a2a-1c37-4c68-9f58-a6a132c3794e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div[2]/table/tbody/tr[3]/td[14]/div</value>
      <webElementGuid>20285bb0-5d7d-4583-a112-5ce4b9ebcecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIRTUAL ACCOUNT'])[2]/following::div[1]</value>
      <webElementGuid>fa514932-b21a-4cac-9b72-cfc8a0cc27a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BCA Virtual Account'])[3]/following::div[2]</value>
      <webElementGuid>48cdf8c5-8c72-47bf-8e25-334e7a1047f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Backend Notification'])[2]/preceding::div[1]</value>
      <webElementGuid>a3e9cca7-35af-452e-9c0f-528f6ec81deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PENDING']/parent::*</value>
      <webElementGuid>0a9ab8d8-b35a-4ae9-a6e5-1e1e9bead530</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[14]/div</value>
      <webElementGuid>72151de8-f4de-41c3-b12d-a70b4d38e09a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'PENDING' or . = 'PENDING')]</value>
      <webElementGuid>fdcc61a2-e070-4e95-855d-3a58c403b7b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
