<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>status_pending</name>
   <tag></tag>
   <elementGuidId>ed112416-a785-442e-ab8b-21c21dd3471a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='contentframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;contentframe&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>24a6acd7-a46c-4d40-84a6-06542fde47dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bb523b4a-059f-488e-ab9f-4c24c853fd8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c081fd3e-e971-4bce-8393-eb983de0a726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>422b6ad5-a7d8-4b4d-9265-4f1d072ee229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>homewelcome</value>
      <webElementGuid>d6e8e084-e6cb-4751-b5c3-1b43cc197235</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contentframe</value>
      <webElementGuid>1f5e87a0-0813-4094-955d-1c5fbccdacd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[2]</value>
      <webElementGuid>1b6eeedf-252b-489c-a308-3d683057b994</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='contentframe']</value>
      <webElementGuid>eb0c3914-7631-4723-ad88-b60173dbc2f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[2]</value>
      <webElementGuid>32d7612e-1cad-4548-8b4f-985dd13de0dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'homewelcome' and @name = 'contentframe']</value>
      <webElementGuid>d402ecc5-67f2-4cc5-a62a-4e4a0c8216b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
