<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>text_VA number</name>
   <tag></tag>
   <elementGuidId>b2f7fb5d-59d2-4d4b-9cee-6676dc3cab96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//frame[@name='contentframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>frame[name=&quot;contentframe&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>c17f327b-2be4-4967-934c-ba47f25f1b2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>657ff4a2-7095-4928-9bc2-5a2a08ec14a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>56a8a1d9-8bba-4892-a336-867f40175222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7034fde8-9146-4876-ae95-3bf5ad03a357</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>homewelcome</value>
      <webElementGuid>a4369a67-6bff-4c06-a25b-34e0b82d0265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contentframe</value>
      <webElementGuid>3e436b0e-3cbc-4eb9-8482-f8a9e0c82fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[2]</value>
      <webElementGuid>f69233b8-55d4-49c2-b6f5-539b01cdaa28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@name='contentframe']</value>
      <webElementGuid>ae573152-8d9d-43e7-9125-de4d34cb4705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[2]</value>
      <webElementGuid>578c3cbc-a785-41ca-bbdc-e83dc155917c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//frame[@src = 'homewelcome' and @name = 'contentframe']</value>
      <webElementGuid>6523cc11-7a43-4abb-8dd3-5310cc060e8b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
