<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>amount</name>
   <tag></tag>
   <elementGuidId>8651ca5f-8e05-4233-a184-5d6cbde23e7c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//vaadin-horizontal-layout[3]/vaadin-text-field</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/body[1]/div[@class=&quot;main-layout&quot;]/vaadin-vertical-layout[1]/vaadin-vertical-layout[1]/vaadin-vertical-layout[1]/vaadin-horizontal-layout[3]/vaadin-text-field[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>vaadin-text-field</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;main-layout&quot;]/vaadin-vertical-layout[1]/vaadin-vertical-layout[1]/vaadin-vertical-layout[1]/vaadin-horizontal-layout[3]/vaadin-text-field[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//vaadin-horizontal-layout[3]/vaadin-text-field</value>
   </webElementXpaths>
</WebElementEntity>
