<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_virtual Account</name>
   <tag></tag>
   <elementGuidId>7d7013e7-1d56-4a7c-9255-a1ee75fa8a4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='virtualAccount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#virtualAccount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1f421988-e195-4194-8331-9acb04cab517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Virtual Account</value>
      <webElementGuid>e4106db6-c675-4a2a-af36-d40ac310eed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>20487129-d694-4d6b-8232-fc03edd13b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>virtualAccount</value>
      <webElementGuid>c59bf84d-42c6-47de-af33-bc6278d6e1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>virtualAccount</value>
      <webElementGuid>083831bd-711c-4350-9c31-f3738708f72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61aaf703-d186-428c-b3c7-8a103283b16e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;virtualAccount&quot;)</value>
      <webElementGuid>b1df6a9d-4581-4cb6-ba2c-9d7ab504e2ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='virtualAccount']</value>
      <webElementGuid>6a00e323-33d7-414d-9d1f-7eb8596e4138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PERMATAVA']/div/div/div/div[2]/input</value>
      <webElementGuid>1c83b0d8-6881-47f5-996d-9f85f56af0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>56514c1d-d6f7-4c87-b848-9ca02d373b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Virtual Account' and @id = 'virtualAccount' and @name = 'virtualAccount' and @type = 'text']</value>
      <webElementGuid>eb0fcb55-752c-4583-9d18-4b43bf233291</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
