<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>strong_AXL65D2C52888334DF6A</name>
   <tag></tag>
   <elementGuidId>1063059d-5ad2-4a18-8c48-55cb01192443</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div[2]/div/div/p[2]/strong</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>731dbdc0-93fa-4c2f-9b30-aefb1338dcd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AXL65D2C52888334DF6A</value>
      <webElementGuid>5a219576-e0ba-41fb-aa37-65c0e16ce15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;content-flex&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;box text-center mt-25&quot;]/p[2]/strong[1]</value>
      <webElementGuid>619473b1-d0c6-479d-a709-8422adbfa574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/page_tagihan BCA/value_invoice</value>
      <webElementGuid>ca26a3dd-d4db-40c4-b656-e3ff31f6d8cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div[2]/div/div/p[2]/strong</value>
      <webElementGuid>5a4db021-4b09-4514-99b7-6e35e1230985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kode Pembayaran'])[1]/preceding::strong[2]</value>
      <webElementGuid>834343a6-1b2e-4f95-9701-d0ca4317ae78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jumlah yang harus dibayar'])[1]/preceding::strong[2]</value>
      <webElementGuid>892b7874-376e-41c2-a5fa-6544f5e62f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AXL65D2C52888334DF6A']/parent::*</value>
      <webElementGuid>4a2c856b-d107-47cb-85c8-e73206b090fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//strong</value>
      <webElementGuid>7e588afe-1dbe-4813-ad59-b34e7cc0fa8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'AXL65D2C52888334DF6A' or . = 'AXL65D2C52888334DF6A')]</value>
      <webElementGuid>b85c79c5-85a5-430e-8857-d62e1c38041a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
