<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>center_MANDIRI VIRTUAL ACCOUNT</name>
   <tag></tag>
   <elementGuidId>1220e11f-26ed-4c46-941d-fb4e215c2dc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='MainForm']/div[2]/div[2]/div[4]/div[3]/center</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>4e47e99a-a324-46e2-9ebb-873d0339b085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MANDIRI VIRTUAL ACCOUNT</value>
      <webElementGuid>8bd0adf4-b2dc-4c37-b890-1295b4b5cf6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainForm&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;col-12 shadow mt-5 bg-white rounded border border-warning&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;col-5 mt-4 mb-4 rounded border border-warning&quot;]/center[1]</value>
      <webElementGuid>b5a8b0c5-f8c5-4130-9235-15736124b305</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MainForm']/div[2]/div[2]/div[4]/div[3]/center</value>
      <webElementGuid>8d8bfa06-0118-49d7-9f22-66f9b30d0fab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BRI VIRTUAL ACCOUNT'])[1]/following::center[1]</value>
      <webElementGuid>93f1b685-9b80-4d52-8481-2f7bd7a1e5af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::center[1]</value>
      <webElementGuid>669e6ce6-d149-44a1-9a1a-fb0c14e2bb51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/center</value>
      <webElementGuid>2ff9810e-175e-4565-893d-33123c1010b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//center[(text() = 'MANDIRI VIRTUAL ACCOUNT' or . = 'MANDIRI VIRTUAL ACCOUNT')]</value>
      <webElementGuid>9b473178-3e4c-4092-bc69-0e59886e2e71</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
