<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>center_ALFAMART PAYMENT CODE</name>
   <tag></tag>
   <elementGuidId>0be180a0-19ba-4d32-9d0e-e56637cb2bed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='MainForm']/div[2]/div[2]/div[2]/div/center</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>36170b83-c6c6-4eb7-9416-e24c8d795b1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALFAMART PAYMENT CODE</value>
      <webElementGuid>e0b30135-76c3-4990-ae5a-236ac687946b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainForm&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;col-12 shadow mt-5 bg-white rounded border border-warning&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;col-5 mt-4 mb-4 rounded border border-warning&quot;]/center[1]</value>
      <webElementGuid>81417aa1-4655-4454-9eae-77dc6184c9a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MainForm']/div[2]/div[2]/div[2]/div/center</value>
      <webElementGuid>3c5b1ed6-f44e-4ab8-8b49-87d7fd45d6ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BNI VIRTUAL ACCOUNT'])[1]/following::center[1]</value>
      <webElementGuid>5f4aaf92-9a45-4ac2-a672-85775e3fe3c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PERMATA VIRTUAL ACCOUNT'])[1]/following::center[2]</value>
      <webElementGuid>7aa0384e-1515-4f12-b855-e54ec5c5dae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INDOMARET PAYMENT CODE'])[1]/preceding::center[1]</value>
      <webElementGuid>73c8b771-3abb-4d27-a59e-a65f2992d58c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/center</value>
      <webElementGuid>3e32de69-1f66-49d8-9b3e-9c0ba1f3b24c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//center[(text() = 'ALFAMART PAYMENT CODE' or . = 'ALFAMART PAYMENT CODE')]</value>
      <webElementGuid>a704e698-5bfd-4efb-9e4c-8776f70d0393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
