<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>center_BRI VIRTUAL ACCOUNT</name>
   <tag></tag>
   <elementGuidId>35eb6b6a-526c-44f5-9231-00611f4c2fc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='MainForm']/div[2]/div[2]/div[4]/div/center</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>dfd8bec4-77ab-4ce5-9cad-ecad8606cbe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BRI VIRTUAL ACCOUNT</value>
      <webElementGuid>bc930da0-4545-4b2e-869e-bd4f8b4ae56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MainForm&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;col-12 shadow mt-5 bg-white rounded border border-warning&quot;]/div[@class=&quot;form-row&quot;]/div[@class=&quot;col-5 mt-4 mb-4 rounded border border-warning&quot;]/center[1]</value>
      <webElementGuid>64bc325a-a1c5-4016-ac63-2019cc343d76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='MainForm']/div[2]/div[2]/div[4]/div/center</value>
      <webElementGuid>5c13f061-755e-4e58-9367-716edfedeaab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BCA VIRTUAL ACCOUNT'])[1]/following::center[1]</value>
      <webElementGuid>8a5aeea9-1979-4623-8aeb-26e9b13c5bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MANDIRI VIRTUAL ACCOUNT'])[1]/preceding::center[1]</value>
      <webElementGuid>b7fb6d2a-4f21-4b67-9e93-d2d261d62694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/center</value>
      <webElementGuid>9d47095d-d382-44c9-b50f-bc9acad1c322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//center[(text() = 'BRI VIRTUAL ACCOUNT' or . = 'BRI VIRTUAL ACCOUNT')]</value>
      <webElementGuid>45681099-23cf-4d63-b5fa-815c6f83cee9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
