<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Virtual Account_virtualAccount</name>
   <tag></tag>
   <elementGuidId>5bce36ea-6934-4bda-892d-339e1bbad564</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='virtualAccount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#virtualAccount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91562742-a281-4485-812c-78bb8ee2e890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Virtual Account</value>
      <webElementGuid>f1359d05-314e-48f1-ba53-f6a516b2dd92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>f1cb69fc-d64e-4e70-878f-e9feba77b36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>virtualAccount</value>
      <webElementGuid>82ca7358-a51d-4475-91a3-a0b84cf3a211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>virtualAccount</value>
      <webElementGuid>5f628170-f1e1-414b-8348-0d86c9ed35f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>906d7560-ba20-4e3b-843a-92682d705350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;virtualAccount&quot;)</value>
      <webElementGuid>ed0c498a-be1a-4fd0-a14f-5f940c0e2628</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='virtualAccount']</value>
      <webElementGuid>4b755e1f-4f9d-4797-bc1e-a0874a1f7d6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PERMATAVA']/div/div/div/div[2]/input</value>
      <webElementGuid>1cd55d93-32eb-49f0-bf69-46358b071998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>16b1974e-ac05-495c-8877-68a674f9f7a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Virtual Account' and @id = 'virtualAccount' and @name = 'virtualAccount' and @type = 'text']</value>
      <webElementGuid>e5001033-c4fe-4d4d-9faf-216be016c3d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
