<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__paymentAmount</name>
   <tag></tag>
   <elementGuidId>c2bb2fac-3d50-40f9-9c72-7192ba33a0ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='paymentAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#paymentAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46ff86a7-d765-495d-bf45-9653aa62dec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Payment Amount</value>
      <webElementGuid>f2f34cfe-091b-42ae-a198-d01c3968c2b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control-sm</value>
      <webElementGuid>ff4866ff-414c-4cca-b353-bc1f0d023bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>paymentAmount</value>
      <webElementGuid>1e567d89-423a-499f-bf37-2fe41b054242</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>paymentAmount</value>
      <webElementGuid>ccd2980b-ae21-485f-b42e-c07160b9e498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e451e68a-7493-4777-b9de-1e0335b0159d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentAmount&quot;)</value>
      <webElementGuid>41eb8dd6-cc1b-4003-a725-c11abbd13ee6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='paymentAmount']</value>
      <webElementGuid>b9e3038a-2761-45dc-80f9-86d0e8806383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='detail']/div[5]/div[3]/input</value>
      <webElementGuid>d7cf7532-c3bd-4b75-a4c8-2c040cd53de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/input</value>
      <webElementGuid>7355c455-5e1d-48ae-8bb8-d3883ade1a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Payment Amount' and @id = 'paymentAmount' and @name = 'paymentAmount' and @type = 'text']</value>
      <webElementGuid>daba3c84-97fa-444c-85da-4ef4107d5c56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
