<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_amount</name>
   <tag></tag>
   <elementGuidId>deb7780c-a3f3-4df1-89be-b1b59db9487d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='trxAmountPermata']/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#trxAmountPermata > h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>4ce2e35a-111b-460c-bf64-b6516bdddd8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>300000</value>
      <webElementGuid>16a4d9b8-5a3d-4a66-a0f3-dc52ee7bb5ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trxAmountPermata&quot;)/h5[1]</value>
      <webElementGuid>f5fedba2-9319-48a2-9464-0157d281497b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trxAmountPermata']/h5</value>
      <webElementGuid>421cac45-82bb-4989-9952-f16910609e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[4]/following::h5[1]</value>
      <webElementGuid>f69d753e-d4fe-40a7-bb0c-893e9f681670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[1]/following::h5[2]</value>
      <webElementGuid>76d2dd25-cf80-48de-aed0-21f5464a17b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment Amount'])[1]/preceding::h5[1]</value>
      <webElementGuid>5f3908db-2563-491d-b6e1-7d8857ae56ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=':'])[5]/preceding::h5[2]</value>
      <webElementGuid>100a9db1-092d-42f7-805f-34d6f88dccd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='300000']/parent::*</value>
      <webElementGuid>845f3cfc-4a11-4336-be8c-1e835ee443d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/h5</value>
      <webElementGuid>a755bfc6-ef04-4868-915a-8024409bcacc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = '300000' or . = '300000')]</value>
      <webElementGuid>5ac466c6-8515-4174-a334-b9632f98c0dd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
